version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  user-server:
    cmds:
      - cd services/user_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o togo cmd/server/main.go
      - defer: cd services/user_service && rm togo
      - docker-compose build user-server
      - docker-compose up user-server

  todo-server:
    cmds:
      - cd services/todo_service && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o togo cmd/server/main.go
      - defer: cd services/todo_service && rm togo
      - docker-compose build todo-server
      - docker-compose up todo-server

  migrate:
    desc: migrate db
    cmds:
      - cd migrate && go run main.go {{.CLI_ARGS}}

  gateway:
    cmds:
      - docker-compose build gateway
      - docker-compose up gateway
