version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  server:
    cmds:
      - cd backend && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o togo cmd/server/main.go
      - defer: cd backend && rm togo
      - docker-compose build server
      - docker-compose up server

  migrate:
    desc: migrate db
    cmds:
      - cd migrate && go run main.go {{.CLI_ARGS}}

  gateway:
    cmds:
      - docker-compose build gateway
      - docker-compose up gateway
